/**
 * migrate-json-to-sqlite
 *
 * Reads every table from database.json and inserts the data into the SQLite
 * database via PrismaClient.
 *
 * Usage (from packages/database/):
 *   npm run migrate:json-to-sqlite
 *
 * Prerequisites:
 *   - Run `npx prisma migrate dev` inside adapters/prisma-sqlite/ first so the
 *     schema is applied and the generated client exists.
 *   - Set DATABASE_URL in .env if the sqlite file is not at the default path.
 *
 * WARNING: This script CLEARS the existing SQLite database before importing.
 * Back up database.sqlite before running if it contains data you want to keep.
 * The operation is NOT wrapped in a single transaction — if it fails mid-way,
 * some tables will be partially populated. Re-run after fixing the root cause.
 */
import '../scripts/load-env.js';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promises as fs } from 'node:fs';

import { PrismaClient } from '../adapters/prisma-sqlite/src/generated/prisma/client.js';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// packages/database/src → packages/database
const dbRoot = path.resolve(__dirname, '..');
const DB_JSON_FILE = path.resolve(dbRoot, 'database/database.json');

const rawUrl = process.env['DATABASE_URL'];
const DB_SQLITE_FILE = rawUrl
  ? rawUrl.replace(/^file:/, '')
  : path.resolve(dbRoot, 'database/database.sqlite');

// Mirrors store.ts DEFAULT_DB so any table absent from an older database.json
// is treated as an empty array rather than undefined, preventing runtime crashes.
const DEFAULT_DB: Record<string, unknown[]> = {
  botSessionCommand: [], botSessionEvent: [], botCredentialDiscord: [],
  botCredentialTelegram: [], botCredentialFacebookPage: [],
  botCredentialFacebookMessenger: [], botSession: [], botAdmin: [],
  botThread: [], botUser: [], fbPageWebhook: [],
  botThreadSession: [], botUserSession: [],
  botUserBanned: [], botThreadBanned: [],
  user: [], session: [], account: [], verification: [],
};

// Narrow helper so array items can be used as Prisma createMany data
function rows<T>(db: Record<string, unknown[]>, key: string): T[] {
  return (db[key] ?? []) as T[];
}

async function main(): Promise<void> {
  console.log('json-to-sqlite migration');
  console.log(`  Input  : ${DB_JSON_FILE}`);
  console.log(`  SQLite : ${DB_SQLITE_FILE}`);
  console.log('');

  // Fail fast if the JSON source is missing — avoids silently nuking SQLite.
  let raw: string;
  try {
    raw = await fs.readFile(DB_JSON_FILE, 'utf-8');
  } catch {
    console.error(`ERROR: ${DB_JSON_FILE} not found.`);
    console.error('Run "npm run migrate:sqlite-to-json" first, or ensure the file exists.');
    process.exit(1);
  }

  const db: Record<string, unknown[]> = {
    ...DEFAULT_DB,
    ...(JSON.parse(raw) as Record<string, unknown[]>),
  };

  const adapter = new PrismaBetterSqlite3({ url: `file:${DB_SQLITE_FILE}` });
  const prisma = new PrismaClient({ adapter } as ConstructorParameters<typeof PrismaClient>[0]);

  // ── Phase 1: Clear existing data (reverse FK dependency order) ──────────────
  // Must delete child records before parents to satisfy SQLite FK constraints.
  // Models with onDelete: Cascade on their user relation (BotSession, BotAdmin,
  // BotCredential*, FbPageWebhook) would cascade automatically on user delete,
  // but explicit deletions here make the order unambiguous and easier to audit.
  console.log('Clearing existing SQLite data…');

  // Wrap ops so unknown columns/tables generated by better-auth plugins gracefully skip rather than crashing the script.
  const safeExec = async <T>(p: Promise<T>): Promise<void> => {
    try { await p; } catch (e: any) { console.warn(`[WARN] ${e.message}`); }
  };

  await safeExec(prisma.botUserBanned.deleteMany());
  await safeExec(prisma.botThreadBanned.deleteMany());
  await safeExec(prisma.botSessionCommand.deleteMany());
  await safeExec(prisma.botSessionEvent.deleteMany());
  await safeExec(prisma.botUserSession.deleteMany());
  await safeExec(prisma.botThreadSession.deleteMany());
  await safeExec(prisma.fbPageWebhook.deleteMany());
  await safeExec(prisma.botCredentialDiscord.deleteMany());
  await safeExec(prisma.botCredentialTelegram.deleteMany());
  await safeExec(prisma.botCredentialFacebookPage.deleteMany());
  await safeExec(prisma.botCredentialFacebookMessenger.deleteMany());
  await safeExec(prisma.botAdmin.deleteMany());
  await safeExec(prisma.botSession.deleteMany());
  await safeExec(prisma.botThread.deleteMany());
  await safeExec(prisma.botUser.deleteMany());
  await safeExec(prisma.verification.deleteMany());
  await safeExec(prisma.account.deleteMany());
  await safeExec(prisma.session.deleteMany());
  await safeExec(prisma.user.deleteMany());

  // ── Phase 2: Insert in topological FK order ──────────────────────────────────
  console.log('Inserting data…');

  // 1. better-auth core tables — no FK deps within the set
  type UserRow    = Parameters<typeof prisma.user.createMany>[0]['data'][number];
  type SessionRow = Parameters<typeof prisma.session.createMany>[0]['data'][number];
  type AccountRow = Parameters<typeof prisma.account.createMany>[0]['data'][number];
  type VerifRow   = Parameters<typeof prisma.verification.createMany>[0]['data'][number];

  const userRows = rows<UserRow>(db, 'user');
  if (userRows.length)    await safeExec(prisma.user.createMany({ data: userRows }));

  const sessionRows = rows<SessionRow>(db, 'session');
  if (sessionRows.length) await safeExec(prisma.session.createMany({ data: sessionRows }));

  const accountRows = rows<AccountRow>(db, 'account');
  if (accountRows.length) await safeExec(prisma.account.createMany({ data: accountRows }));

  const verifRows = rows<VerifRow>(db, 'verification');
  if (verifRows.length)   await safeExec(prisma.verification.createMany({ data: verifRows }));

  // 2. BotUser — referenced by BotThread (M:M), BotUserSession, BotUserBanned
  type BotUserRow = Parameters<typeof prisma.botUser.createMany>[0]['data'][number];
  const botUserRows = rows<BotUserRow>(db, 'botUser');
  if (botUserRows.length) await safeExec(prisma.botUser.createMany({ data: botUserRows }));

  // 3. BotThread — M:M participants/admins reference BotUser so users must exist first.
  //    JSON stores these as plain string[] arrays; Prisma requires connect syntax.
  //    createMany cannot handle nested relations, so we use individual create() calls.
  type JsonThread = {
    platformId: number; id: string; name: string | null; isGroup: boolean;
    memberCount: number | null; avatarUrl: string | null;
    createdAt?: Date; updatedAt?: Date;
    participants?: string[]; admins?: string[];
  };
  const botThreadRows = rows<JsonThread>(db, 'botThread');
  for (const t of botThreadRows) {
    const { participants = [], admins =[], ...threadScalars } = t;
    await safeExec(prisma.botThread.create({
      data: {
        ...threadScalars,
        // connect IDs that already exist — a missing ID means the botUser row was
        // never synced, so we skip it rather than aborting the entire migration.
        participants: participants.length
          ? { connect: participants.map((id) => ({ id })) }
          : undefined,
        admins: admins.length
          ? { connect: admins.map((id) => ({ id })) }
          : undefined,
      },
    }));
  }

  // 4. BotSession, BotAdmin — FK to user (onDelete: Cascade)
  type BotSessionRow = Parameters<typeof prisma.botSession.createMany>[0]['data'][number];
  type BotAdminRow   = Parameters<typeof prisma.botAdmin.createMany>[0]['data'][number];

  const botSessionRows = rows<BotSessionRow>(db, 'botSession');
  if (botSessionRows.length) await safeExec(prisma.botSession.createMany({ data: botSessionRows }));

  const botAdminRows = rows<BotAdminRow>(db, 'botAdmin');
  if (botAdminRows.length) await safeExec(prisma.botAdmin.createMany({ data: botAdminRows }));

  // 5. Credentials — FK to user (onDelete: Cascade)
  type DiscordCredRow    = Parameters<typeof prisma.botCredentialDiscord.createMany>[0]['data'][number];
  type TelegramCredRow   = Parameters<typeof prisma.botCredentialTelegram.createMany>[0]['data'][number];
  type FbPageCredRow     = Parameters<typeof prisma.botCredentialFacebookPage.createMany>[0]['data'][number];
  type FbMsgCredRow      = Parameters<typeof prisma.botCredentialFacebookMessenger.createMany>[0]['data'][number];

  const discordCreds = rows<DiscordCredRow>(db, 'botCredentialDiscord');
  if (discordCreds.length)    await safeExec(prisma.botCredentialDiscord.createMany({ data: discordCreds }));

  const telegramCreds = rows<TelegramCredRow>(db, 'botCredentialTelegram');
  if (telegramCreds.length)   await safeExec(prisma.botCredentialTelegram.createMany({ data: telegramCreds }));

  const fbPageCreds = rows<FbPageCredRow>(db, 'botCredentialFacebookPage');
  if (fbPageCreds.length)     await safeExec(prisma.botCredentialFacebookPage.createMany({ data: fbPageCreds }));

  const fbMsgCreds = rows<FbMsgCredRow>(db, 'botCredentialFacebookMessenger');
  if (fbMsgCreds.length)      await safeExec(prisma.botCredentialFacebookMessenger.createMany({ data: fbMsgCreds }));

  // 6. Session join tables — FK to BotUser and BotThread which now exist
  type BotUserSessionRow   = Parameters<typeof prisma.botUserSession.createMany>[0]['data'][number];
  type BotThreadSessionRow = Parameters<typeof prisma.botThreadSession.createMany>[0]['data'][number];

  const botUserSessionRows = rows<BotUserSessionRow>(db, 'botUserSession');
  if (botUserSessionRows.length)   await safeExec(prisma.botUserSession.createMany({ data: botUserSessionRows }));

  const botThreadSessionRows = rows<BotThreadSessionRow>(db, 'botThreadSession');
  if (botThreadSessionRows.length) await safeExec(prisma.botThreadSession.createMany({ data: botThreadSessionRows }));

  // 7. FbPageWebhook — FK to user
  type FbWebhookRow = Parameters<typeof prisma.fbPageWebhook.createMany>[0]['data'][number];
  const fbWebhookRows = rows<FbWebhookRow>(db, 'fbPageWebhook');
  if (fbWebhookRows.length) await safeExec(prisma.fbPageWebhook.createMany({ data: fbWebhookRows }));

  // 8. Per-session command/event overrides — no FK to user in schema (composite PK only)
  type BotSessionCommandRow = Parameters<typeof prisma.botSessionCommand.createMany>[0]['data'][number];
  type BotSessionEventRow   = Parameters<typeof prisma.botSessionEvent.createMany>[0]['data'][number];

  const botSessionCommandRows = rows<BotSessionCommandRow>(db, 'botSessionCommand');
  if (botSessionCommandRows.length) await safeExec(prisma.botSessionCommand.createMany({ data: botSessionCommandRows }));

  const botSessionEventRows = rows<BotSessionEventRow>(db, 'botSessionEvent');
  if (botSessionEventRows.length)   await safeExec(prisma.botSessionEvent.createMany({ data: botSessionEventRows }));

  // 9. Ban records — no FK to user in schema (composite PK only, not a Prisma relation)
  // BotUserBanned and BotThreadBanned have no timestamp columns in the Prisma schema.
  // JSON data written by older schema versions may carry updatedAt/createdAt fields
  // that Prisma rejects as unknown arguments — pick only the declared columns explicitly.
  type RawBanned = Record<string, unknown>;

  const rawUserBanned = rows<RawBanned>(db, 'botUserBanned');
  if (rawUserBanned.length) {
    await safeExec(prisma.botUserBanned.createMany({
      data: rawUserBanned.map(({ userId, platformId, sessionId, botUserId, isBanned, reason }) => ({
        userId:    userId    as string,
        platformId: platformId as number,
        sessionId: sessionId as string,
        botUserId: botUserId as string,
        isBanned:  isBanned  as boolean,
        reason:    (reason ?? null) as string | null,
      })),
    }));
  }

  const rawThreadBanned = rows<RawBanned>(db, 'botThreadBanned');
  if (rawThreadBanned.length) {
    await safeExec(prisma.botThreadBanned.createMany({
      data: rawThreadBanned.map(({ userId, platformId, sessionId, botThreadId, isBanned, reason }) => ({
        userId:      userId      as string,
        platformId:  platformId  as number,
        sessionId:   sessionId   as string,
        botThreadId: botThreadId as string,
        isBanned:    isBanned    as boolean,
        reason:      (reason ?? null) as string | null,
      })),
    }));
  }

  console.log('Migration complete. Row counts:');
  for (const [table, tableRows] of Object.entries(db)) {
    if (tableRows.length > 0) {
      console.log(`  ${table.padEnd(34)} ${tableRows.length}`);
    }
  }
  console.log(`\nSQLite database updated: ${DB_SQLITE_FILE}`);

  await prisma.$disconnect();
}

main().catch((err: unknown) => {
  console.error('Migration failed:', err);
  process.exit(1);
});
